In [3]:
import numpy as np

In [8]:
np.__version__

'1.26.3'

np. + tab tuşu (Fonksiyonlar çıkar)

np.abs? (Ne işe yaradığını gösterir)

In [10]:
# absolute(mutlak)
np.abs(-5)

5

In [11]:
ilk_liste = [1,2,3,4,5]

In [12]:
ilk_liste

[1, 2, 3, 4, 5]

In [15]:
# np.array() fonksiyonu kullanılarak ilk_liste adlı Python listesi bir NumPy dizisine dönüştürülür
ilk_dizi = np.array(ilk_liste)

In [16]:
ilk_dizi.max()

5

In [18]:
iki_boyutlu_dizi = np.array([[1,2,3],[4,5,6]])

In [19]:
iki_boyutlu_dizi

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.full(shape=(3,2), fill_value=5)

array([[5, 5],
       [5, 5],
       [5, 5]])

## Rassal Veri Oluşturma

In [26]:
np.random.seed()
r1 = np.random.randint(low=1, high=10, size=3) 
r1

array([1, 6, 3])

In [27]:
r1.shape

(3,)

In [31]:
# size(3,5) 3 satır 5 sütundan oluşan veri tahmini.
r2=np.random.randint(10, size=(3,5))
r2

array([[3, 0, 5, 9, 3],
       [3, 2, 0, 1, 4],
       [4, 5, 5, 0, 1]])

In [33]:
# Satırı ve sütunu olduğundan 3 boyutlu.
r2.shape

(3, 5)

In [34]:
# Üç boyutlu.
r3=np.random.randint(10, size=(3,5,2))
r3

array([[[5, 6],
        [7, 8],
        [2, 4],
        [8, 7],
        [1, 8]],

       [[5, 2],
        [6, 9],
        [6, 8],
        [5, 9],
        [6, 1]],

       [[5, 8],
        [0, 3],
        [6, 3],
        [6, 3],
        [1, 6]]])

## İndeksleme

In [36]:
# 0. satır 1. sütun.
r2[0,1]

0

In [38]:
# Sondan alır.
r2[-1,-1]

1

In [41]:
# r2[start:stop:step]
r2[0,1:3]


array([0, 5])

In [43]:
# arange (doğal sayı dizisi.) start stop step yazılır.
np.arange(3,10,2)

array([3, 5, 7, 9])

In [44]:
# Tüm satırları, sütunları ters alma.
np.arange(3,10,2)[::-1]

array([9, 7, 5, 3])

In [45]:
a = np.array([1,2,3])
b = np.array([4,6,8])

In [46]:
np.add(a,b)

array([ 5,  8, 11])

In [48]:
# a'nın tüm elemanlarına 5 ekleme.
np.add(a,5)

array([6, 7, 8])

In [49]:
np.absolute(a)

array([1, 2, 3])

# Mantıksal Sınama

In [53]:
# a'nın 2'den küçük değerlerini getir.
a[a < 2]

array([1])

In [56]:
# a<2 elemanlarını dizi yap.
np.sum (a[a<2])

1

In [60]:
# Küçükten büyüğe.
np.sort(a)

array([1, 2, 3])

In [62]:
# 0'dan başlayıp 10'da biten 20 sayı.
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])