<img src="../img/logistic_regression.png" width=500 heigth=250>

β0 ---> Regresyon çizgisinin y eksenini kestiği nokta. (x'in 0 olduğu noktada y kaçtır sorusunun cevabı β0'dır.)

β1 ---> Regresyon çizgisinin eğimini verir.(Katsayısını verir.)

hata(e1) ---> Çizgiden sapmalar hatayı gösterir.

    Eğer y değişkeni eğer sürekli verilerden oluşuyorsa regresyon modeli kurmak için kullanılacak modeldir.

    y değişkeni her zaman sürekli verilerden oluşmaz.

    y değeri kesikli verilerden oluşursa 0 ve 1'lerden oluşur.

    Lojistik regresyonda hedef değişkenlerin 0 ve 1 olduğu durumlarla ilgilenilir.

<img src="../img/logistic_regression_1.png" width=500 heigth=250>

<img src="../img/logistic_regression_2.png" width=500 heigth=250>

<img src="../img/logistic_regression_3.png" width=500 heigth=250>

<img src="../img/logistic_regression_4.png" width=500 heigth=250>

<img src="../img/logistic_regression_5.png" width=500 heigth=250>

<img src="../img/logistic_regression_6.png" width=500 heigth=250>

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.linear_model import LogisticRegression 
from sklearn.preprocessing import OneHotEncoder 

In [3]:
dataset = pd.read_excel("../data/kredi_veriseti.xlsx")

In [34]:
dataset.head()

cinsiyet  yas  maas  kredi
0    Erkek   22  2200      0
1    Erkek   38  2300      0
2    Kadın   29  4600      0
3    Kadın   30  6000      0
4    Erkek   22  7900      0

    One hot encoding 
Kategorik verilerin temsilini kolaylaştırır.

In [36]:
one_hot = OneHotEncoder(handle_unknown='ignore')
one_hot_cinsiyet = one_hot.fit_transform(dataset['cinsiyet'].values.reshape(-1,1)).toarray()

In [37]:
one_hot_cinsiyet

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.

In [38]:
one_hot.categories_

[array(['Erkek', 'Kadın'], dtype=object)]

In [39]:
one_hot_df = pd.DataFrame(one_hot_cinsiyet, columns = one_hot.categories_)

In [40]:
one_hot_df.head()

Erkek Kadın
0   1.0   0.0
1   1.0   0.0
2   0.0   1.0
3   0.0   1.0
4   1.0   0.0

In [41]:
one_hot_df2 = dataset.join(one_hot_df)

In [42]:
one_hot_df2.head()

cinsiyet  yas  maas  kredi  (Erkek,)  (Kadın,)
0    Erkek   22  2200      0       1.0       0.0
1    Erkek   38  2300      0       1.0       0.0
2    Kadın   29  4600      0       0.0       1.0
3    Kadın   30  6000      0       0.0       1.0
4    Erkek   22  7900      0       1.0       0.0

In [43]:
one_hot_df2.drop('cinsiyet', axis=1, inplace=True)

In [44]:
one_hot_df2.head()

yas  maas  kredi  (Erkek,)  (Kadın,)
0   22  2200      0       1.0       0.0
1   38  2300      0       1.0       0.0
2   29  4600      0       0.0       1.0
3   30  6000      0       0.0       1.0
4   22  7900      0       1.0       0.0

In [45]:
X = one_hot_df2.drop('kredi', axis=1)
y = one_hot_df2['kredi']

In [46]:
from sklearn.model_selection import train_test_split

In [50]:
x_train, x_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.33,
                                                    random_state=42) # ---> 4 yeni dataframe

In [51]:
x_train.head()

yas  maas  (Erkek,)  (Kadın,)
258   61  9800       0.0       1.0
177   28  2500       1.0       0.0
119   44  6200       1.0       0.0
194   31  9200       1.0       0.0
229   45  8300       0.0       1.0

In [55]:
y_train.head()

258    1
177    0
119    0
194    0
229    1
Name: kredi, dtype: int64

In [56]:
(X.shape[0]/3)*2

266.6666666666667

In [58]:
x_test.shape

(132, 4)

### Ölçeklendirme

In [59]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [60]:
sc = StandardScaler()

In [65]:
x_train

yas   maas  (Erkek,)  (Kadın,)
258   61   9800       0.0       1.0
177   28   2500       1.0       0.0
119   44   6200       1.0       0.0
194   31   9200       1.0       0.0
229   45   8300       0.0       1.0
..   ...    ...       ...       ...
71    27   3000       0.0       1.0
106   29   3800       0.0       1.0
270   46  13600       0.0       1.0
348   42   8000       1.0       0.0
102   35   8900       0.0       1.0

[268 rows x 4 columns]

In [67]:
# Convert feature names to strings
x_train.columns = x_train.columns.astype(str)
x_test.columns = x_test.columns.astype(str)

# Fit and transform using the StandardScaler
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

In [69]:
X_train

array([[ 2.0052225 ,  0.72479792, -0.97785703,  0.97785703],
       [-1.22740379, -1.43119212,  1.02264438, -1.02264438],
       [ 0.33993017, -0.33843005,  1.02264438, -1.02264438],
       ...,
       [ 0.53584692,  1.84709411, -0.97785703,  0.97785703],
       [ 0.14401343,  0.19318394,  1.02264438, -1.02264438],
       [-0.54169518,  0.45899093, -0.97785703,  0.97785703]])

### Modelleme Aşaması

In [72]:
model = LogisticRegression(random_state=0)
model.fit(X_train,y_train)

LogisticRegression(random_state=0)

### Tahmin Sonuçları

In [73]:
y_pred = model.predict(X_test)

In [74]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0])

In [76]:
y_test.values

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0])

Performans Değerlendirmesi

In [78]:
# Sınıflamalarda,performans değerlendirmelerinde kullanılan matrixler.
from sklearn.metrics import confusion_matrix, classification_report

In [79]:
confusion_matrix(y_true=y_test, y_pred=y_pred)

array([[78,  2],
       [19, 33]])